# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderCore', '0002_auto_20171114_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='title', max_length=32),
        ),
    ]
