# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spiderCore', '0003_auto_20171114_1721'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
